<template>
  <div>
    123
    <CardImg :consumes="consumes"></CardImg>
  </div>

</template>

<script>
import CardImg from "./temp/CardImg";
export default {
  name: "TestPage",
  components: {CardImg},
  data(){
    return{
      show:true,
      consumes: 123
    }
  }
}
</script>

<style scoped>
.block {
  background-color: limegreen;
  width: 5rem;
  height: 5rem;
  margin: auto auto;
}
.roll-out-left {
  -webkit-animation: roll-out-left 0.6s ease-in both;
  animation: roll-out-left 0.6s ease-in both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-8-17 17:54:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation roll-out-left
 * ----------------------------------------
 */
@-webkit-keyframes roll-out-left {
  0% {
    -webkit-transform: translateX(0) rotate(0deg);
    transform: translateX(0) rotate(0deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-1000px) rotate(-540deg);
    transform: translateX(-1000px) rotate(-540deg);
    opacity: 0;
  }
}
@keyframes roll-out-left {
  0% {
    -webkit-transform: translateX(0) rotate(0deg);
    transform: translateX(0) rotate(0deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-1000px) rotate(-540deg);
    transform: translateX(-1000px) rotate(-540deg);
    opacity: 0;
  }
}

</style>
